# Generated by Django 3.1.2 on 2020-10-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_job_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
