# Generated by Django 3.1.2 on 2020-10-23 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_sent',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
