# Generated by Django 3.1.2 on 2020-10-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20201023_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='images',
            field=models.ImageField(upload_to='article_photos/'),
        ),
    ]
