# Generated by Django 3.1.2 on 2020-10-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20201022_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='article_photos/'),
        ),
    ]
