# Generated by Django 3.1.2 on 2020-10-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20201023_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body_text',
            field=models.TextField(),
        ),
    ]
