# Generated by Django 3.1.2 on 2020-10-23 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_job_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('body_text', models.TextField()),
                ('time_sent', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
